-- video-player/run.lua
--
-- Plays a short pre-converted clip on an Advanced Monitor with synced
-- audio: one "frames.ccv" text file (pixel-art frames back to back, same
-- per-pixel format as ../photo-viewer's .nfp) plus one "audio.dfpwm"
-- file (CC:Tweaked's native compressed audio format, played through a
-- Speaker). This is the same trick the CC:Tweaked community has used for
-- years to play clips on a monitor (search "Bad Apple ComputerCraft" for
-- what the result looks like) -- NOT a real video codec, and NOT a live
-- YouTube stream -- there is no video decoder inside CC:Tweaked's Lua
-- sandbox, and no such thing as "paste a YouTube link, watch it live"
-- here. See this folder's README.md for the honest full picture,
-- including what converts a source video into this format (something
-- you run on YOUR OWN computer, not in Minecraft -- see
-- ../../tools/video_to_ccv.py).
--
-- Don't wget this file directly to install it -- see install.lua in this
-- same folder, or the repo root README's "Installing a script in-game".
--
-- WIRING: an Advanced Monitor (color needed for this to look like
-- anything) + a Speaker, both attached to this computer.
--
-- CLIP_NAME below picks which clips/<name>/ subfolder to play -- add a
-- new clip by running ../../tools/video_to_ccv.py, pushing the result
-- under a new clips/<name>/ folder, and changing this one constant.

local SCRIPT_VERSION = "2026-09-01.1"

local CLIP_NAME = "sample"
local BASE_URL = "https://raw.githubusercontent.com/quentinjuarez/atm10/main/scripts/video-player/clips/" .. CLIP_NAME .. "/"
local FRAMES_URL = BASE_URL .. "frames.ccv"
local AUDIO_URL = BASE_URL .. "audio.dfpwm"
local LOOP_PAUSE_SECONDS = 3 -- kiosk mode: replays automatically after finishing
local LOG_FILE = "video-player.log"
local LOG_MAX_LINES = 50

-- ---------------------------------------------------------------------
-- Logging: same pattern as every other script in this repo.
-- ---------------------------------------------------------------------

local logLines = {}

local function log(fmt, ...)
  local line = ("[%s] " .. fmt):format(os.date("%H:%M:%S"), ...)
  print(line)
  table.insert(logLines, line)
  if #logLines > LOG_MAX_LINES then
    table.remove(logLines, 1)
  end
  local f = fs.open(LOG_FILE, "w")
  if f then
    f.write(table.concat(logLines, "\n"))
    f.close()
  end
end

-- ---------------------------------------------------------------------
-- .ccv parsing/drawing -- .ccv is this repo's own bundle format: one
-- header line "CCV1 <width> <height> <fps> <frameCount>" followed by
-- frameCount*height rows, each row using the exact same hex-digit-per-
-- pixel convention as ../photo-viewer's .nfp files (see that folder's
-- README.md format ADR -- same reasoning applies here).
-- ---------------------------------------------------------------------

local BLIT_TO_COLOR = {
  ["0"] = colors.white,     ["1"] = colors.orange, ["2"] = colors.magenta,
  ["3"] = colors.lightBlue, ["4"] = colors.yellow, ["5"] = colors.lime,
  ["6"] = colors.pink,      ["7"] = colors.gray,    ["8"] = colors.lightGray,
  ["9"] = colors.cyan,      ["a"] = colors.purple,  ["b"] = colors.blue,
  ["c"] = colors.brown,     ["d"] = colors.green,   ["e"] = colors.red,
  ["f"] = colors.black,
}

local function parseCcv(text)
  local lines = {}
  for line in (text .. "\n"):gmatch("(.-)\n") do
    table.insert(lines, line)
  end

  local header = lines[1]
  local width, height, fps, frameCount = header:match("^CCV1 (%d+) (%d+) (%d+) (%d+)$")
  if not width then
    error("frames.ccv has no valid CCV1 header -- was it generated by video_to_ccv.py?", 0)
  end
  width, height, fps, frameCount = tonumber(width), tonumber(height), tonumber(fps), tonumber(frameCount)

  local expectedRows = frameCount * height
  -- lines[1] is the header, frame rows start at lines[2].
  if #lines - 1 < expectedRows then
    error(("frames.ccv is truncated: header claims %d frame(s) of %d rows, only %d row(s) present")
      :format(frameCount, height, #lines - 1), 0)
  end

  return { width = width, height = height, fps = fps, frameCount = frameCount, rows = lines, rowOffset = 1 }
end

-- Draws frame `i` (1-indexed), clipped to the monitor's actual size.
-- Same same-color-RUN batching as ../photo-viewer/run.lua's drawImage --
-- see that folder's README.md ADR for why this isn't paintutils.drawImage.
local function drawFrame(monitor, clip, i, monW, monH)
  monitor.setBackgroundColor(colors.black)
  local firstRow = clip.rowOffset + (i - 1) * clip.height
  local maxY = math.min(clip.height, monH)
  local maxX = math.min(clip.width, monW)
  for y = 1, maxY do
    local row = clip.rows[firstRow + y]
    local runStart, runColor = 1, nil
    for x = 1, maxX + 1 do
      local color = nil
      if x <= maxX then
        local ch = row:sub(x, x)
        color = ch ~= "" and ch ~= " " and BLIT_TO_COLOR[ch] or nil
      end
      if color ~= runColor then
        if runColor then
          monitor.setCursorPos(runStart, y)
          monitor.setBackgroundColor(runColor)
          monitor.write(string.rep(" ", x - runStart))
        end
        runStart, runColor = x, color
      end
    end
  end
end

local function drawMessage(monitor, text, color)
  monitor.setBackgroundColor(colors.black)
  monitor.clear()
  monitor.setCursorPos(1, 1)
  monitor.setTextColor(color or colors.white)
  monitor.write(text)
end

-- ---------------------------------------------------------------------
-- Everything below runs inside one pcall so ANY failure gets logged to
-- file, not just flashed on a screen nobody's watching.
-- ---------------------------------------------------------------------

local ok, err = pcall(function()
  local monitor = peripheral.find("monitor")
  if not monitor then
    error("no monitor peripheral found -- attach one to this computer", 0)
  end
  monitor.setTextScale(1)
  local monW, monH = monitor.getSize()

  local speaker = peripheral.find("speaker")
  if not speaker then
    error("no speaker peripheral found -- attach one to this computer", 0)
  end

  drawMessage(monitor, "Loading '" .. CLIP_NAME .. "'...", colors.gray)

  local fetchOk, clip = pcall(function()
    local h = http.get(FRAMES_URL)
    if not h then error("could not fetch frames.ccv -- does clips/" .. CLIP_NAME .. "/ exist?", 0) end
    local text = h.readAll()
    h.close()
    return parseCcv(text)
  end)
  if not fetchOk then
    error("failed to load clip frames: " .. tostring(clip), 0)
  end

  log("READY v%s -- clip '%s': %dx%d, %d frame(s) @ %dfps",
    SCRIPT_VERSION, CLIP_NAME, clip.width, clip.height, clip.frameCount, clip.fps)

  local frameIntervalMs = 1000 / clip.fps

  local function videoLoop()
    for i = 1, clip.frameCount do
      local frameStart = os.epoch("utc")
      local drawOk, drawErr = pcall(drawFrame, monitor, clip, i, monW, monH)
      if not drawOk then
        log("DRAW ERROR (frame %d): %s", i, tostring(drawErr))
      end
      local waitMs = frameIntervalMs - (os.epoch("utc") - frameStart)
      if waitMs > 0 then
        os.sleep(waitMs / 1000)
      end
    end
  end

  -- Own pcall around the WHOLE audio loop, not per-chunk: a failure here
  -- (missing speaker, bad audio.dfpwm, network hiccup mid-stream) should
  -- silence the audio and let the video keep playing solo, not abort the
  -- clip -- see this folder's README.md's "video and audio fail
  -- independently" ADR.
  local function audioLoop()
    local audioOk, audioErr = pcall(function()
      local dfpwm = require("cc.audio.dfpwm")
      local decoder = dfpwm.make_decoder()
      local h = http.get(AUDIO_URL, nil, true)
      if not h then error("could not fetch audio.dfpwm", 0) end
      while true do
        local chunk = h.read(16 * 1024)
        if not chunk then break end
        local buffer = decoder(chunk)
        while not speaker.playAudio(buffer) do
          os.pullEvent("speaker_audio_empty")
        end
      end
      h.close()
    end)
    if not audioOk then
      log("AUDIO ERROR: %s (video continues without sound)", tostring(audioErr))
    end
  end

  -- Installed via startup.lua like every other computer in this repo, so
  -- this needs to behave like a kiosk, not a one-shot: loop the clip
  -- forever instead of finishing and sitting idle until someone reboots
  -- it. Frame data (`clip`) was fetched once above and is replayed from
  -- memory every loop; audio re-opens AUDIO_URL each time since its HTTP
  -- stream is consumed as it plays. Each playthrough gets its own pcall
  -- so one bad loop (a network hiccup fetching audio, say) doesn't end
  -- the kiosk permanently -- same per-cycle resilience pattern as
  -- ../powah-energy-monitor's scripts.
  while true do
    -- waitForAll, not waitForAny: if audio errors out early it just
    -- finishes silently while video keeps playing -- waitForAny would
    -- kill the video the instant audio (or video) finishes first, which
    -- is wrong when one runs short.
    local playOk, playErr = pcall(parallel.waitForAll, videoLoop, audioLoop)
    if not playOk then
      log("PLAYBACK ERROR: %s", tostring(playErr))
    end
    drawMessage(monitor, "-- " .. CLIP_NAME .. " -- replaying in " .. LOOP_PAUSE_SECONDS .. "s --", colors.gray)
    os.sleep(LOOP_PAUSE_SECONDS)
  end
end)

if not ok then
  log("CRASHED: %s", tostring(err))
end
